version: "3"
services:
  django:
    image: deckapp/django:latest
    command: "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - "${APP_CODE_PATH_HOST}:/code"
    ports:
      - "${DJANGO_HOST_HTTP_PORT}:8000"
    depends_on:
      - "postgres"
  postgres:
    build:
      context: "./postgres"
      args:
        - "POSTGRES_VERSION=${POSTGRES_VERSION}"
    volumes:
      - "${DATA_PATH_HOST}/postgres:/var/lib/postgresql/data"
      - "${POSTGRES_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d"
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - "POSTGRES_DB=${POSTGRES_DB}"
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "GITLAB_POSTGRES_INIT=${GITLAB_POSTGRES_INIT}"
      - "GITLAB_POSTGRES_USER=${GITLAB_POSTGRES_USER}"
      - "GITLAB_POSTGRES_PASSWORD=${GITLAB_POSTGRES_PASSWORD}"
      - "GITLAB_POSTGRES_DB=${GITLAB_POSTGRES_DB}"
      - "JUPYTERHUB_POSTGRES_INIT=${JUPYTERHUB_POSTGRES_INIT}"
      - "JUPYTERHUB_POSTGRES_USER=${JUPYTERHUB_POSTGRES_USER}"
      - "JUPYTERHUB_POSTGRES_PASSWORD=${JUPYTERHUB_POSTGRES_PASSWORD}"
      - "JUPYTERHUB_POSTGRES_DB=${JUPYTERHUB_POSTGRES_DB}"
      - "SONARQUBE_POSTGRES_INIT=${SONARQUBE_POSTGRES_INIT}"
      - "SONARQUBE_POSTGRES_DB=${SONARQUBE_POSTGRES_DB}"
      - "SONARQUBE_POSTGRES_USER=${SONARQUBE_POSTGRES_USER}"
      - "SONARQUBE_POSTGRES_PASSWORD=${SONARQUBE_POSTGRES_PASSWORD}"
      - "POSTGRES_CONFLUENCE_INIT=${CONFLUENCE_POSTGRES_INIT}"
      - "POSTGRES_CONFLUENCE_DB=${CONFLUENCE_POSTGRES_DB}"
      - "POSTGRES_CONFLUENCE_USER=${CONFLUENCE_POSTGRES_USER}"
      - "POSTGRES_CONFLUENCE_PASSWORD=${CONFLUENCE_POSTGRES_PASSWORD}"
volumes: {}
