version: '3'
services:
  django:
    build:
      context: './django'
      args:
        - 'USER_ID=${USER_ID}'
        - 'GROUP_ID=${GROUP_ID}'
    command: '/usr/local/bin/autoreload python manage.py runserver 0.0.0.0:8000'
    volumes:
      - '${APP_CODE_PATH_HOST}:/code'
    ports:
      - '${DJANGO_HOST_HTTP_PORT}:8000'
volumes: {}
