name: Django 

on:
  schedule:
  - cron:  '46 22 * * *'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Django-AMD64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image Django
      run: docker-compose -f "docker-compose.yml" up -d --build
    - name: Web site test
      run:  |
        # sh /home/ubuntu/script/curl-check.sh url "http://localhost:35399" stack-name "Django"
        #curl -i http://localhost:35399
    # - name: Destroy container and file
    #   run:  |
    #     docker-compose down
    #     echo "y" | docker image prune -a
    #     sudo rm -rf /tmp/django/
    - name: notify slack
      id: slack
      uses: slack/webhook-action@v3
      # https://api.slack.com/apps/<your-app-id>/incoming-webhooks
      if: ${{ SUCCESS() }}
      with:
        channel-id: '#github_action_status' # slack channel #alerts-test
        payload: |
          '{"text": "Hello! This is a notification from GitHub Actions.", "attachments": [{"text": "Choose an option:", "fallback": "You are unable to choose", "callback_id": "button_click", "color": "#3AA3E3", "attachment_type": "default", "actions": [{"name": "yes", "text": "Yes", "type": "button", "value": "yes"}, {"name": "no", "text": "No", "type": "button", "value": "no"}]}]}'
      env:
        webhook_url: ${{ secrets.SLACK_WEBHOOK_URL_FAIL }}
        # SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
