name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Django:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the image Adminer
        run: docker-compose build
        